app:
  messages:
    ipNotFound: "IP address not found"
spring:
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/profiles/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/profiles/**
          filters:
            - StripPrefix=1

